{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cart-deploy.serviceAccountName" . }}
  labels:
{{ include "cart-deploy.labels" . | indent 4 }}
{{- end -}}
